trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    command: publish
    projects: cdstoolbox.csproj
    zipAfterPublish: true
    modifyOutputPath: false
    arguments: '-c $(buildConfiguration) -p:futureversion=$(Build.BuildNumber) -o "$(Build.ArtifactStagingDirectory)/app"'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Microsoft Partner Network(56e76164-b3f9-445a-93ce-25c79f5ad59a)'
    appType: 'webApp'
    WebAppName: 'cdstoolbox'
    deployToSlotOrASE: true
    ResourceGroupName: 'cdstoolboxio'
    SlotName: 'test'
    packageForLinux: '$(Build.ArtifactStagingDirectory)/app/*.zip'